/**
 * Small, dependency-free helpers for the grocery catalog: tidy a typed name
 * into a canonical one, and guess an icon for a brand-new item from the words
 * in it. The catalog remembers the icon after that, so this only has to be
 * good enough for the first time something is added — an admin can correct it.
 */

export function normalizeName(raw: string): string {
  const trimmed = raw.trim().replace(/\s+/g, " ").slice(0, 60);
  if (!trimmed) return "";
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
}

// Keyword -> emoji. First match wins, so put specific words before general
// ones. Matched against the lower-cased name as whole-word-ish substrings.
const ICONS: [RegExp, string][] = [
  // Order matters — first match wins, so keep specific terms above general ones
  // (e.g. "sweet potato" before "potato", "peanut butter" before "butter").
  // --- Kairos specific icons first: more-specific phrases win over the
  //     generic emoji rules below via the head-noun/length tie-break. ---
  [/\b(chocolate\s+chips|choc\s+chips|chocolate\s+chip|white\s+chocolate\s+chips|peanut\s+butter\s+chips|baking\s+chips)\b/, "kairos:chocolate-chips"],
  [/\b(coffee\s+filters|coffee\s+filter)\b/, "kairos:coffee-filters"],
  [/\b(k\s+cups|k-cups|kcups|coffee\s+pods|keurig\s+pods)\b/, "kairos:k-cups"],
  [/\b(plums|plum)\b/, "kairos:plums"],
  [/\b(pomegranate)\b/, "kairos:pomegranate"],
  [/\b(cannoli|cannolis)\b/, "kairos:cannoli"],
  [/\b(doritos|nacho\s+chips|nachos)\b/, "kairos:doritos"],
  [/\b(sunflower\s+seeds|sunflower\s+seed)\b/, "kairos:sunflower-seeds"],
  [/\b(almonds|almond)\b/, "kairos:almonds"],
  [/\b(cashews|cashew)\b/, "kairos:cashews"],
  [/\b(walnuts|walnut)\b/, "kairos:walnuts"],
  [/\b(pistachios|pistachio)\b/, "kairos:pistachios"],
  [/\b(beef\s+jerky)\b/, "kairos:beef-jerky"],
  [/\b(turkey\s+jerky)\b/, "kairos:turkey-jerky"],
  [/\b(protein\s+bar|protein\s+bars|energy\s+bar)\b/, "kairos:protein-bar"],
  [/\b(granola)\b/, "kairos:granola"],
  [/\b(corn\s+meal|cornmeal)\b/, "kairos:corn-meal"],
  [/\b(heavy\s+cream|heavy\s+whipping\s+cream|whipping\s+cream)\b/, "kairos:heavy-cream"],
  [/\b(whipped\s+cream\s+can|whipped\s+cream|whip\s+cream|reddi\s+wip)\b/, "kairos:whipped-cream-can"],
  [/\b(whipped\s+cream\s+tub|cool\s+whip|whipped\s+topping|whip\s+cream\s+tub)\b/, "kairos:whipped-cream-tub"],
  [/\b(sliced\s+cheese|cheese\s+slices|american\s+cheese|cold\s+cut\s+cheese|deli\s+cheese)\b/, "kairos:sliced-cheese"],
  [/\b(black\s+olives|black\s+olive)\b/, "kairos:black-olives"],
  [/\b(distilled\s+water)\b/, "kairos:distilled-water"],
  [/\b(motor\s+oil|engine\s+oil)\b/, "kairos:motor-oil"],
  [/\b(avocado\s+oil)\b/, "kairos:avocado-oil"],
  [/\b(car\s+oil\s+filter|oil\s+filter)\b/, "kairos:car-oil-filter"],
  [/\b(car\s+air\s+filter|air\s+filter|cabin\s+air\s+filter)\b/, "kairos:car-air-filter"],
  [/\b(birthday\s+candles|birthday\s+candle|candles)\b/, "kairos:birthday-candles"],
  [/\b(iceberg\s+lettuce|iceberg|head\s+lettuce)\b/, "kairos:iceberg-lettuce"],
  [/\b(backpacking\s+food|freeze\s+dried|freeze-dried\s+meal|dehydrated\s+meal|camping\s+food)\b/, "kairos:backpacking-food"],
  [/\b(orange\s+juice|oj)\b/, "kairos:orange-juice"],
  [/\b(apple\s+juice)\b/, "kairos:apple-juice"],
  [/\b(grape\s+juice)\b/, "kairos:grape-juice"],
  [/\b(cranberry\s+juice)\b/, "kairos:cranberry-juice"],
  [/\b(lemonade)\b/, "kairos:lemonade"],
  [/\b(sweet\s+tea)\b/, "kairos:sweet-tea"],
  [/\b(iced\s+tea|ice\s+tea)\b/, "kairos:iced-tea"],
  [/\b(kombucha)\b/, "kairos:kombucha"],
  [/\b(hot\s+chocolate|hot\s+cocoa|cocoa)\b/, "kairos:hot-chocolate"],
  [/\b(chocolate\s+milk)\b/, "kairos:chocolate-milk"],
  [/\b(apple\s+cider|cider)\b/, "kairos:apple-cider"],
  [/\b(coconut\s+water)\b/, "kairos:coconut-water"],
  [/\b(milk\s+carton|gallon\s+of\s+milk|carton\s+of\s+milk|milk)\b/, "kairos:milk-carton"],
  [/\b(coffee\s+bag|coffee|coffee\s+beans|ground\s+coffee|whole\s+bean)\b/, "kairos:coffee-bag"],
  [/\b(wine)\b/, "kairos:wine"],
  [/\b(beer|ale|lager)\b/, "kairos:beer"],
  [/\b(champagne|prosecco|sparkling\s+wine)\b/, "kairos:champagne"],
  [/\b(whiskey|whisky|scotch)\b/, "kairos:whiskey"],
  [/\b(bourbon)\b/, "kairos:bourbon"],
  [/\b(vodka)\b/, "kairos:vodka"],
  [/\b(gin)\b/, "kairos:gin"],
  [/\b(rum)\b/, "kairos:rum"],
  [/\b(tequila)\b/, "kairos:tequila"],
  [/\b(cocktail|mixed\s+drink|margarita)\b/, "kairos:cocktail"],
  [/\b(salmon)\b/, "kairos:salmon"],
  [/\b(tuna)\b/, "kairos:tuna"],
  [/\b(tilapia)\b/, "kairos:tilapia"],
  [/\b(cod|codfish)\b/, "kairos:cod"],
  [/\b(catfish)\b/, "kairos:catfish"],
  [/\b(mahi\s+mahi|mahi|dorado)\b/, "kairos:mahi-mahi"],
  [/\b(shrimp|prawns|prawn)\b/, "kairos:shrimp"],
  [/\b(crab\s+legs|king\s+crab|snow\s+crab)\b/, "kairos:crab-legs"],
  [/\b(lobster\s+tail|lobster\s+tails)\b/, "kairos:lobster-tail"],
  [/\b(scallops|scallop)\b/, "kairos:scallops"],
  [/\b(mussels|mussel)\b/, "kairos:mussels"],
  [/\b(clams|clam)\b/, "kairos:clams"],
  [/\b(crawfish|crayfish|crawdad)\b/, "kairos:crawfish"],
  [/\b(fish\s+fillet|fish\s+fillets)\b/, "kairos:fish-fillet"],
  [/\b(fish\s+sticks|fish\s+stick|fish\s+fingers)\b/, "kairos:fish-sticks"],
  [/\b(canned\s+tuna|tuna\s+can|can\s+of\s+tuna)\b/, "kairos:canned-tuna"],
  [/\b(imitation\s+crab|surimi|crab\s+stick)\b/, "kairos:imitation-crab"],
  [/\b(air\s+freshener|febreze)\b/, "kairos:air-freshener"],
  [/\b(allergy\s+medicine|antihistamine|allergy\s+pills|claritin|zyrtec|benadryl)\b/, "kairos:allergy-medicine"],
  [/\b(almond\s+milk)\b/, "kairos:almond-milk"],
  [/\b(asparagus)\b/, "kairos:asparagus"],
  [/\b(baby\s+food)\b/, "kairos:baby-food"],
  [/\b(baby\s+formula)\b/, "kairos:baby-formula"],
  [/\b(baby\s+wipes)\b/, "kairos:baby-wipes"],
  [/\b(baking\s+powder)\b/, "kairos:baking-powder"],
  [/\b(baking\s+soda)\b/, "kairos:baking-soda"],
  [/\b(bandages)\b/, "kairos:bandages"],
  [/\b(batteries\s+pack|batteries)\b/, "kairos:batteries-pack"],
  [/\b(bbq\s+sauce)\b/, "kairos:bbq-sauce"],
  [/\b(black\s+pepper)\b/, "kairos:black-pepper"],
  [/\b(bleach)\b/, "kairos:bleach"],
  [/\b(block\s+cheese|cheese\s+block)\b/, "kairos:block-cheese"],
  [/\b(body\s+wash)\b/, "kairos:body-wash"],
  [/\b(breadcrumbs)\b/, "kairos:breadcrumbs"],
  [/\b(brisket)\b/, "kairos:brisket"],
  [/\b(broth)\b/, "kairos:broth"],
  [/\b(brown\s+sugar)\b/, "kairos:brown-sugar"],
  [/\b(brussels\s+sprouts|brussel\s+sprouts)\b/, "kairos:brussels-sprouts"],
  [/\b(butter\s+sticks|stick\s+butter)\b/, "kairos:butter-sticks"],
  [/\b(canned\s+beans|black\s+beans|kidney\s+beans)\b/, "kairos:canned-beans"],
  [/\b(canned\s+goods)\b/, "kairos:canned-goods"],
  [/\b(canned\s+tomatoes|diced\s+tomatoes)\b/, "kairos:canned-tomatoes"],
  [/\b(cantaloupe)\b/, "kairos:cantaloupe"],
  [/\b(casserole)\b/, "kairos:casserole"],
  [/\b(cat\s+food)\b/, "kairos:cat-food"],
  [/\b(cat\s+litter)\b/, "kairos:cat-litter"],
  [/\b(cauliflower)\b/, "kairos:cauliflower"],
  [/\b(celery)\b/, "kairos:celery"],
  [/\b(cheddar)\b/, "kairos:cheddar"],
  [/\b(chicken\s+breast|chicken\s+breasts)\b/, "kairos:chicken-breast"],
  [/\b(chicken\s+thighs)\b/, "kairos:chicken-thighs"],
  [/\b(chicken\s+wings)\b/, "kairos:chicken-wings"],
  [/\b(chili\s+powder)\b/, "kairos:chili-powder"],
  [/\b(chips\s+bag|potato\s+chips|chips)\b/, "kairos:chips-bag"],
  [/\b(cinnamon)\b/, "kairos:cinnamon"],
  [/\b(cleaning\s+spray)\b/, "kairos:cleaning-spray"],
  [/\b(coconut\s+milk)\b/, "kairos:coconut-milk"],
  [/\b(cold\s+cuts|lunch\s+meat|deli\s+meat)\b/, "kairos:cold-cuts"],
  [/\b(conditioner)\b/, "kairos:conditioner"],
  [/\b(cooking\s+spray|nonstick\s+spray)\b/, "kairos:cooking-spray"],
  [/\b(cornstarch)\b/, "kairos:cornstarch"],
  [/\b(cottage\s+cheese)\b/, "kairos:cottage-cheese"],
  [/\b(cotton\s+swabs)\b/, "kairos:cotton-swabs"],
  [/\b(crackers\s+box|crackers)\b/, "kairos:crackers-box"],
  [/\b(cream\s+cheese)\b/, "kairos:cream-cheese"],
  [/\b(creamer)\b/, "kairos:creamer"],
  [/\b(cumin)\b/, "kairos:cumin"],
  [/\b(deli\s+ham|sliced\s+ham)\b/, "kairos:deli-ham"],
  [/\b(deodorant)\b/, "kairos:deodorant"],
  [/\b(diapers)\b/, "kairos:diapers"],
  [/\b(dinner\s+rolls)\b/, "kairos:dinner-rolls"],
  [/\b(dish\s+soap)\b/, "kairos:dish-soap"],
  [/\b(dishwasher\s+pods)\b/, "kairos:dishwasher-pods"],
  [/\b(dog\s+food)\b/, "kairos:dog-food"],
  [/\b(dryer\s+sheets|fabric\s+softener)\b/, "kairos:dryer-sheets"],
  [/\b(egg\s+noodles)\b/, "kairos:egg-noodles"],
  [/\b(eggs\s+carton|eggs|carton\s+of\s+eggs|dozen\s+eggs)\b/, "kairos:eggs-carton"],
  [/\b(energy\s+drink)\b/, "kairos:energy-drink"],
  [/\b(english\s+muffins|english\s+muffin)\b/, "kairos:english-muffins"],
  [/\b(fajitas)\b/, "kairos:fajitas"],
  [/\b(feminine\s+care)\b/, "kairos:feminine-care"],
  [/\b(feta)\b/, "kairos:feta"],
  [/\b(filet\s+mignon|tenderloin)\b/, "kairos:filet-mignon"],
  [/\b(first\s+aid|first\s+aid\s+kit)\b/, "kairos:first-aid"],
  [/\b(floss)\b/, "kairos:floss"],
  [/\b(flour)\b/, "kairos:flour"],
  [/\b(foil)\b/, "kairos:foil"],
  [/\b(frozen\s+dinner)\b/, "kairos:frozen-dinner"],
  [/\b(frozen\s+pizza)\b/, "kairos:frozen-pizza"],
  [/\b(frozen\s+vegetables|frozen\s+veggies|frozen\s+veg)\b/, "kairos:frozen-veggies"],
  [/\b(garlic\s+powder)\b/, "kairos:garlic-powder"],
  [/\b(granola\s+bars|granola\s+bar)\b/, "kairos:granola-bars"],
  [/\b(green\s+beans|string\s+beans)\b/, "kairos:green-beans"],
  [/\b(green\s+onion|scallion|scallions|spring\s+onion)\b/, "kairos:green-onion"],
  [/\b(ground\s+beef|hamburger\s+meat|minced\s+beef|ground\s+chuck)\b/, "kairos:ground-beef"],
  [/\b(ground\s+sausage|breakfast\s+sausage|sausage\s+meat)\b/, "kairos:ground-sausage"],
  [/\b(ground\s+turkey)\b/, "kairos:ground-turkey"],
  [/\b(guacamole)\b/, "kairos:guacamole"],
  [/\b(hamburger\s+buns|burger\s+buns)\b/, "kairos:hamburger-buns"],
  [/\b(hand\s+soap)\b/, "kairos:hand-soap"],
  [/\b(honey\s+jar|honey)\b/, "kairos:honey-jar"],
  [/\b(hot\s+dog\s+buns|hotdog\s+buns)\b/, "kairos:hot-dog-buns"],
  [/\b(hummus)\b/, "kairos:hummus"],
  [/\b(ice)\b/, "kairos:ice"],
  [/\b(italian\s+bread)\b/, "kairos:italian-bread"],
  [/\b(italian\s+seasoning)\b/, "kairos:italian-seasoning"],
  [/\b(jam)\b/, "kairos:jam"],
  [/\b(ketchup)\b/, "kairos:ketchup"],
  [/\b(lasagna)\b/, "kairos:lasagna"],
  [/\b(laundry\s+detergent)\b/, "kairos:laundry-detergent"],
  [/\b(light\s+bulbs|light\s+bulb|lightbulb)\b/, "kairos:light-bulbs"],
  [/\b(lotion|body\s+lotion)\b/, "kairos:lotion"],
  [/\b(mac\s+and\s+cheese|macaroni\s+and\s+cheese|mac\s+n\s+cheese)\b/, "kairos:mac-and-cheese"],
  [/\b(macaroni)\b/, "kairos:macaroni"],
  [/\b(mayonnaise|mayo)\b/, "kairos:mayo"],
  [/\b(meatballs)\b/, "kairos:meatballs"],
  [/\b(meatloaf)\b/, "kairos:meatloaf"],
  [/\b(medicine)\b/, "kairos:medicine"],
  [/\b(mozzarella)\b/, "kairos:mozzarella"],
  [/\b(mustard)\b/, "kairos:mustard"],
  [/\b(napkins)\b/, "kairos:napkins"],
  [/\b(oatmeal\s+canister|oatmeal|oats)\b/, "kairos:oatmeal-canister"],
  [/\b(olive\s+oil|evoo)\b/, "kairos:olive-oil"],
  [/\b(olives\s+jar|olives)\b/, "kairos:olives-jar"],
  [/\b(onion\s+powder)\b/, "kairos:onion-powder"],
  [/\b(oregano)\b/, "kairos:oregano"],
  [/\b(pain\s+reliever|ibuprofen|acetaminophen|tylenol|advil|aspirin)\b/, "kairos:pain-reliever"],
  [/\b(pancake\s+mix|waffle\s+mix)\b/, "kairos:pancake-mix"],
  [/\b(paper\s+plates)\b/, "kairos:paper-plates"],
  [/\b(paper\s+towels)\b/, "kairos:paper-towels"],
  [/\b(paprika)\b/, "kairos:paprika"],
  [/\b(parmesan)\b/, "kairos:parmesan"],
  [/\b(pasta\s+sauce)\b/, "kairos:pasta-sauce"],
  [/\b(peanut\s+butter)\b/, "kairos:peanut-butter"],
  [/\b(penne)\b/, "kairos:penne"],
  [/\b(pepperoni)\b/, "kairos:pepperoni"],
  [/\b(pet\s+treats)\b/, "kairos:pet-treats"],
  [/\b(pickles\s+jar|pickles)\b/, "kairos:pickles-jar"],
  [/\b(pita\s+bread|pita)\b/, "kairos:pita-bread"],
  [/\b(plastic\s+cutlery|plastic\s+utensils|plastic\s+silverware)\b/, "kairos:plastic-cutlery"],
  [/\b(plastic\s+wrap)\b/, "kairos:plastic-wrap"],
  [/\b(pork\s+chops)\b/, "kairos:pork-chops"],
  [/\b(protein\s+powder)\b/, "kairos:protein-powder"],
  [/\b(ravioli)\b/, "kairos:ravioli"],
  [/\b(razors)\b/, "kairos:razors"],
  [/\b(red\s+onion)\b/, "kairos:red-onion"],
  [/\b(red\s+potato)\b/, "kairos:red-potato"],
  [/\b(ribeye\s+steak|ribeye|rib\s+eye)\b/, "kairos:ribeye-steak"],
  [/\b(ribs)\b/, "kairos:ribs"],
  [/\b(rice\s+bag|rice)\b/, "kairos:rice-bag"],
  [/\b(romaine\s+lettuce|romaine)\b/, "kairos:romaine-lettuce"],
  [/\b(rotisserie\s+chicken|roast\s+chicken|whole\s+chicken)\b/, "kairos:rotisserie-chicken"],
  [/\b(russet\s+potato|russet)\b/, "kairos:russet-potato"],
  [/\b(salad\s+dressing)\b/, "kairos:salad-dressing"],
  [/\b(salami)\b/, "kairos:salami"],
  [/\b(salsa)\b/, "kairos:salsa"],
  [/\b(shampoo)\b/, "kairos:shampoo"],
  [/\b(shredded\s+cheese)\b/, "kairos:shredded-cheese"],
  [/\b(sirloin\s+steak)\b/, "kairos:sirloin-steak"],
  [/\b(soda\s+bottle|soda|soft\s+drink)\b/, "kairos:soda-bottle"],
  [/\b(soup\s+bowl|soup)\b/, "kairos:soup-bowl"],
  [/\b(sour\s+cream)\b/, "kairos:sour-cream"],
  [/\b(soy\s+sauce)\b/, "kairos:soy-sauce"],
  [/\b(spaghetti)\b/, "kairos:spaghetti"],
  [/\b(sparkling\s+water)\b/, "kairos:sparkling-water"],
  [/\b(spice\s+jar|spices|spice)\b/, "kairos:spice-jar"],
  [/\b(sponges|dish\s+sponge)\b/, "kairos:sponges"],
  [/\b(sports\s+drink)\b/, "kairos:sports-drink"],
  [/\b(stir[-\s]?fry)\b/, "kairos:stir-fry"],
  [/\b(storage\s+bags)\b/, "kairos:storage-bags"],
  [/\b(string\s+cheese)\b/, "kairos:string-cheese"],
  [/\b(sugar)\b/, "kairos:sugar"],
  [/\b(sunscreen|sunblock)\b/, "kairos:sunscreen"],
  [/\b(supplements)\b/, "kairos:supplements"],
  [/\b(syrup)\b/, "kairos:syrup"],
  [/\b(tacos\s+plate|tacos)\b/, "kairos:tacos-plate"],
  [/\b(tissues)\b/, "kairos:tissues"],
  [/\b(tofu)\b/, "kairos:tofu"],
  [/\b(tomato\s+paste)\b/, "kairos:tomato-paste"],
  [/\b(toothpaste)\b/, "kairos:toothpaste"],
  [/\b(tortilla\s+chips)\b/, "kairos:tortilla-chips"],
  [/\b(tortillas|flour\s+tortillas)\b/, "kairos:tortillas"],
  [/\b(trash\s+bags)\b/, "kairos:trash-bags"],
  [/\b(vegetable\s+oil|canola\s+oil)\b/, "kairos:vegetable-oil"],
  [/\b(vinegar)\b/, "kairos:vinegar"],
  [/\b(vitamins)\b/, "kairos:vitamins"],
  [/\b(yellow\s+onion)\b/, "kairos:yellow-onion"],
  [/\b(yogurt)\b/, "kairos:yogurt"],
  [/\b(ziti)\b/, "kairos:ziti"],
  [/\b(zucchini)\b/, "kairos:zucchini"],
  // Fruit
  [/\bsorbet\b|island way/, "ic:sorbet"],
  [/\bsweet potato|\byams?\b/, "🍠"],
  [/\bapples?\b/, "🍎"],
  [/\bbananas?\b/, "🍌"],
  [/\boranges?|mandarin|tangerine|clementine\b/, "🍊"],
  [/\b(lemons?|limes?)\b/, "🍋"],
  [/\bstrawberr/, "🍓"],
  [/\b(blue|rasp|black|cran)berr(y|ies)\b/, "🫐"],
  [/\bberr(y|ies)\b/, "🫐"],
  [/\bgrapes?\b/, "🍇"],
  [/\b(watermelon|melon|cantaloupe|honeydew)\b/, "🍉"],
  [/\bcherr(y|ies)\b/, "🍒"],
  [/\b(peach|peaches|nectarine)\b/, "🍑"],
  [/\bpears?\b/, "🍐"],
  [/\bmango(es)?\b/, "🥭"],
  [/\bpineapple/, "🍍"],
  [/\bcoconut/, "🥥"],
  [/\bkiwi/, "🥝"],
  [/\bavocado/, "🥑"],
  [/\btomato/, "🍅"],
  // Vegetables
  [/\bpotato/, "🥔"],
  [/\bcarrots?\b/, "🥕"],
  [/\b(onions?|shallots?|scallions?)\b/, "🧅"],
  [/\bgarlic\b/, "🧄"],
  [/\bchil(i|li|e)|jalape|serrano|habanero\b/, "🌶️"],
  [/\bpeppers?\b/, "🫑"],
  [/\bcorn\b/, "🌽"],
  [/\bbroccoli\b/, "🥦"],
  [/\b(lettuce|spinach|kale|cabbage|greens?|salad|arugula|collard)\b/, "🥬"],
  [/\b(cucumber|pickles?)\b/, "🥒"],
  [/\bmushroom/, "🍄"],
  [/\b(eggplant|aubergine)\b/, "🍆"],
  [/\b(peas|edamame|snap peas)\b/, "🫛"],
  [/\b(beans?|lentils?|chickpeas?|legume)/, "🫘"],
  [/\bolives?\b/, "🫒"],
  // Dairy & eggs
  [/\bmilk\b/, "🥛"],
  [/\beggs?\b/, "🥚"],
  [/\b(peanut|almond|nut) butter\b/, "🥜"],
  [/\bbutter\b/, "🧈"],
  [/\b(feta|mozz?arella|cheddar|parmesan|parmigiano|gouda|brie|ricotta|provolone|swiss|cotija|queso|halloumi|colby|monterey)\b/, "🧀"],
  [/\bcheese\b/, "🧀"],
  [/\byogh?urt\b/, "🥛"],
  [/\bice ?cream\b/, "🍦"],
  [/\bcreamer?\b/, "🥛"],
  // Bakery
  [/\b(bread|toast|bagel|buns?|rolls?|loaf)\b/, "🍞"],
  [/\b(baguette|sourdough)\b/, "🥖"],
  [/\bcroissant\b/, "🥐"],
  [/\bpretzel/, "🥨"],
  [/\bwaffles?\b/, "🧇"],
  [/\b(pancakes?|crepes?)\b/, "🥞"],
  [/\b(donut|doughnut)/, "🍩"],
  [/\b(cookie|biscuit)/, "🍪"],
  [/\b(cupcake|muffin)/, "🧁"],
  [/\bcakes?\b/, "🍰"],
  [/\bpies?\b/, "🥧"],
  // Meat & seafood
  [/\b(chicken|poultry|turkey)\b/, "🍗"],
  [/\b(beef|steak|mince)\b/, "🥩"],
  [/\b(bacon|ham|pork|prosciutto)\b/, "🥓"],
  [/\b(sausage|hot ?dog|bratwurst|frank)/, "🌭"],
  [/\b(lamb|ribs?)\b/, "🍖"],
  [/\b(salmon|tuna|cod|tilapia|fish)\b/, "🐟"],
  [/\b(shrimp|prawns?)\b/, "🍤"],
  [/\bcrab\b/, "🦀"],
  [/\blobster\b/, "🦞"],
  [/\b(squid|calamari)\b/, "🦑"],
  [/\b(oysters?|clams?|mussels?|scallops?)\b/, "🦪"],
  // Pantry & grains
  [/\brice\b/, "🍚"],
  [/\b(ramen|udon|soba)\b/, "🍜"],
  [/\b(pasta|spaghetti|noodles?|macaroni|penne|lasagna)\b/, "🍝"],
  [/\b(cereal|oats|granola|muesli)\b/, "🥣"],
  [/\bflour\b/, "🌾"],
  [/\bsugar\b/, "🧂"],
  [/\bsalt\b/, "🧂"],
  [/\b(cinnamon|paprika|cumin|nutmeg|seasoning|spice)\b/, "🧂"],
  [/\bhoney\b/, "🍯"],
  [/\b(oil|vinegar)\b/, "🧴"],
  [/\b(peanut|almond|walnut|cashew|pistachio|nuts?)\b/, "🥜"],
  [/\b(soup|broth|stock|canned|sauce|salsa|ketchup|mustard|mayo|gravy)\b/, "🥫"],
  // Snacks & sweets
  [/\b(chips|crisps|fries)\b/, "🍟"],
  [/\bpopcorn\b/, "🍿"],
  [/\b(chocolate|cocoa)\b/, "🍫"],
  [/\b(cand(y|ies)|sweets|gummy|lollipop)\b/, "🍬"],
  [/\bgum\b/, "🍬"],
  [/\bcrackers?\b/, "🍘"],
  // Drinks
  [/\bcoffee\b/, "☕"],
  [/\btea\b/, "🍵"],
  [/\bjuice\b/, "🧃"],
  [/\b(bottled water|water bottle)\b/, "ic:waterbottle"],
  [/\bprotein\b/, "ic:protein"],
  [/\b(gatorade|powerade|sports drink|electrolyte|pedialyte|energy drink)\b/, "🥤"],
  [/\bwater\b/, "💧"],
  [/\b(soda|cola|pop|soft drink|sparkling)\b/, "🥤"],
  [/\bwine\b/, "🍷"],
  [/\b(beer|ale|lager)\b/, "🍺"],
  // Prepared / frozen
  [/\bpizza\b/, "🍕"],
  [/\bsushi\b/, "🍣"],
  [/\btacos?\b/, "🌮"],
  [/\b(burrito|wrap)\b/, "🌯"],
  [/\b(dumpling|gyoza|potsticker)/, "🥟"],
  [/\b(herbs?|basil|parsley|cilantro|thyme|rosemary|oregano|mint)\b/, "🌿"],
  // Household & personal
  [/\b(paper towels?|kitchen roll)\b/, "ic:papertowel"],
  [/\btoilet paper\b/, "🧻"],
  [/\b(tissues?|kleenex)\b/, "🧻"],
  [/\b(napkins?|serviette)\b/, "ic:napkin"],
  [/\b(detergent|cleaner|bleach|sanitizer|disinfectant)\b/, "🧴"],
  [/\b(soap|shampoo|conditioner|body ?wash)\b/, "🧼"],
  [/\b(sponge|scrubber)\b/, "🧽"],
  [/\b(toothpaste|toothbrush|floss)\b/, "🪥"],
  [/\bbatter(y|ies)\b/, "🔋"],
  [/\b(shirt|clothes|clothing|socks|pants|jacket|underwear)\b/, "👕"],
  [/\b(shoes|boots|sneakers)\b/, "👟"],
  [/\b(medicine|pills?|vitamins?|supplements?|magnesium|melatonin|probiotics?|collagen|omega|fish oil|tylenol|advil|ibuprofen|aspirin)\b/, "💊"],
  [/\b(diapers?|nappy|nappies)\b/, "📦"],
  [/\b(formula|baby bottle)\b/, "🍼"],
  [/\bflowers?\b/, "💐"],
  [/\b(light ?bulb|bulb)\b/, "💡"],
  [/\b(trash|garbage|bin bags?)\b/, "🗑️"],
  [/\b(dog|cat|pet)\b/, "🦴"],
];

/** Distinct icons the guesser knows, in first-seen order \u2014 the palette the
 *  admin icon picker offers. An item can still be set to any typed emoji. */
export const ICON_CHOICES: string[] = Array.from(new Set(ICONS.map(([, icon]) => icon)));

/** Icon library for the admin picker \u2014 a broad, searchable pool decoupled from
 *  the guesser above. `keywords` is what the picker's search box matches against
 *  (substring, case-insensitive). Any emoji can still be set by pasting it. */
export type IconLibraryEntry = { icon: string; keywords: string };
export const GROCERY_ICON_LIBRARY: IconLibraryEntry[] = [
  // Fruit
  { icon: "🍎", keywords: "apple fruit red" },
  { icon: "🍏", keywords: "green apple fruit" },
  { icon: "🍌", keywords: "banana fruit" },
  { icon: "🍊", keywords: "orange mandarin tangerine clementine citrus fruit" },
  { icon: "🍋", keywords: "lemon lime citrus" },
  { icon: "🍓", keywords: "strawberry berry fruit" },
  { icon: "🫐", keywords: "blueberry blackberry raspberry cranberry berry berries" },
  { icon: "🍇", keywords: "grapes fruit raisin" },
  { icon: "🍉", keywords: "watermelon melon cantaloupe honeydew fruit" },
  { icon: "🍒", keywords: "cherry cherries fruit" },
  { icon: "🍑", keywords: "peach nectarine apricot fruit" },
  { icon: "🍐", keywords: "pear fruit" },
  { icon: "🥭", keywords: "mango fruit tropical" },
  { icon: "🍍", keywords: "pineapple fruit tropical" },
  { icon: "🥥", keywords: "coconut" },
  { icon: "🥝", keywords: "kiwi fruit" },
  { icon: "🥑", keywords: "avocado guacamole" },
  // Vegetables
  { icon: "🍅", keywords: "tomato" },
  { icon: "🥔", keywords: "potato spud" },
  { icon: "🍠", keywords: "sweet potato yam" },
  { icon: "🥕", keywords: "carrot" },
  { icon: "🧅", keywords: "onion shallot scallion leek" },
  { icon: "🧄", keywords: "garlic garlic powder" },
  { icon: "🫚", keywords: "ginger root turmeric" },
  { icon: "🌶️", keywords: "chili chile pepper hot jalapeno serrano habanero spicy" },
  { icon: "🫑", keywords: "bell pepper capsicum" },
  { icon: "🌽", keywords: "corn maize" },
  { icon: "🥦", keywords: "broccoli" },
  { icon: "🥬", keywords: "lettuce spinach kale cabbage greens salad arugula collard bok choy" },
  { icon: "🥒", keywords: "cucumber pickle zucchini courgette" },
  { icon: "🍄", keywords: "mushroom" },
  { icon: "🍆", keywords: "eggplant aubergine" },
  { icon: "🫛", keywords: "peas edamame snap peas green beans" },
  { icon: "🫘", keywords: "beans lentils chickpeas legume kidney black" },
  { icon: "🫒", keywords: "olives" },
  // Dairy & eggs
  { icon: "🥛", keywords: "milk dairy" },
  { icon: "🥚", keywords: "egg eggs" },
  { icon: "🧈", keywords: "butter margarine ghee" },
  { icon: "🧀", keywords: "cheese feta mozzarella cheddar parmesan gouda brie ricotta provolone swiss cottage queso" },
  { icon: "🍦", keywords: "ice cream gelato frozen dessert" },
  // Bakery
  { icon: "🍞", keywords: "bread toast bagel bun roll loaf sandwich" },
  { icon: "🥖", keywords: "baguette sourdough french bread" },
  { icon: "🥐", keywords: "croissant pastry" },
  { icon: "🥨", keywords: "pretzel" },
  { icon: "🧇", keywords: "waffle" },
  { icon: "🥞", keywords: "pancake crepe" },
  { icon: "🍩", keywords: "donut doughnut" },
  { icon: "🍪", keywords: "cookie biscuit" },
  { icon: "🧁", keywords: "cupcake muffin" },
  { icon: "🍰", keywords: "cake dessert" },
  { icon: "🥧", keywords: "pie" },
  // Meat & seafood
  { icon: "🍗", keywords: "chicken poultry turkey drumstick wing" },
  { icon: "🥩", keywords: "beef steak mince ground beef meat" },
  { icon: "🥓", keywords: "bacon ham pork prosciutto" },
  { icon: "🌭", keywords: "sausage hot dog bratwurst frank kielbasa" },
  { icon: "🍖", keywords: "lamb ribs pork chop meat bone" },
  { icon: "🐟", keywords: "fish salmon tuna cod tilapia halibut trout" },
  { icon: "🍤", keywords: "shrimp prawn" },
  { icon: "🦀", keywords: "crab" },
  { icon: "🦞", keywords: "lobster" },
  { icon: "🦑", keywords: "squid calamari octopus" },
  { icon: "🦪", keywords: "oyster clam mussel scallop shellfish" },
  // Pantry & grains
  { icon: "🍚", keywords: "rice grain" },
  { icon: "🍜", keywords: "ramen udon soba noodle soup" },
  { icon: "🍝", keywords: "pasta spaghetti noodle macaroni penne lasagna" },
  { icon: "🥣", keywords: "cereal oats oatmeal granola muesli bowl porridge" },
  { icon: "🧂", keywords: "salt seasoning pepper" },
  { icon: "🍯", keywords: "honey syrup maple jam preserves molasses" },
  { icon: "🥜", keywords: "nuts peanut almond walnut cashew pistachio peanut butter" },
  // Snacks & sweets
  { icon: "🍟", keywords: "fries chips crisps" },
  { icon: "🍿", keywords: "popcorn" },
  { icon: "🍫", keywords: "chocolate cocoa candy bar" },
  { icon: "🍬", keywords: "candy sweets gummy lollipop gum mints" },
  { icon: "🍘", keywords: "crackers rice cracker" },
  // Drinks
  { icon: "☕", keywords: "coffee espresso latte" },
  { icon: "🍵", keywords: "tea green tea matcha" },
  { icon: "🧃", keywords: "juice box orange juice apple juice oj capri sun" },
  { icon: "🥤", keywords: "sports drink gatorade powerade electrolyte energy drink soda cup straw slushie" },
  { icon: "💧", keywords: "water" },
  { icon: "ic:waterbottle", keywords: "water bottle bottled water" },
  { icon: "ic:protein", keywords: "protein shake powder whey" },
  { icon: "🍷", keywords: "wine red white rose" },
  { icon: "🍺", keywords: "beer ale lager cider" },
  // Prepared / frozen / herbs
  { icon: "🍕", keywords: "pizza" },
  { icon: "🍣", keywords: "sushi sashimi" },
  { icon: "🥪", keywords: "sandwich sub deli" },
  { icon: "🥗", keywords: "salad" },
  { icon: "🌮", keywords: "taco" },
  { icon: "🌯", keywords: "burrito wrap" },
  { icon: "🥟", keywords: "dumpling gyoza potsticker wonton" },
  { icon: "🍱", keywords: "bento meal frozen dinner" },
  { icon: "🍛", keywords: "curry stew" },
  { icon: "🌿", keywords: "herbs basil parsley cilantro thyme rosemary oregano mint fresh" },
  // Household
  { icon: "🧻", keywords: "toilet paper tp bath tissue" },
  { icon: "ic:papertowel", keywords: "paper towel kitchen roll" },
  { icon: "ic:napkin", keywords: "napkin serviette" },
  { icon: "🧽", keywords: "sponge scrubber dish" },
  { icon: "🪥", keywords: "toothbrush toothpaste floss dental" },
  { icon: "🔋", keywords: "battery batteries aa aaa" },
  { icon: "💡", keywords: "light bulb lightbulb lamp" },
  { icon: "🗑️", keywords: "trash garbage bin bags waste" },
  { icon: "👕", keywords: "shirt clothes clothing socks pants jacket underwear" },
  { icon: "👟", keywords: "shoes boots sneakers" },
  // Health, baby, pet, misc
  { icon: "💊", keywords: "medicine pills vitamin supplement magnesium melatonin probiotic omega fish oil advil tylenol aspirin" },
  { icon: "🩹", keywords: "bandage band aid first aid" },
  { icon: "🍼", keywords: "formula baby bottle infant" },
  { icon: "💐", keywords: "flowers bouquet plant" },
  { icon: "📦", keywords: "other misc box generic package" },
  // --- Kairos colorful PNG icons (kairos:<slug>) ---
  { icon: "kairos:air-freshener", keywords: "air freshener febreze" },
  { icon: "kairos:allergy-medicine", keywords: "allergy medicine antihistamine claritin zyrtec benadryl allergy" },
  { icon: "kairos:almond-milk", keywords: "almond milk" },
  { icon: "kairos:asparagus", keywords: "asparagus" },
  { icon: "kairos:baby-food", keywords: "baby food" },
  { icon: "kairos:baby-formula", keywords: "baby formula" },
  { icon: "kairos:baby-wipes", keywords: "baby wipes" },
  { icon: "kairos:baking-powder", keywords: "baking powder" },
  { icon: "kairos:baking-soda", keywords: "baking soda" },
  { icon: "kairos:bandages", keywords: "bandages" },
  { icon: "kairos:batteries-pack", keywords: "batteries pack battery aa aaa" },
  { icon: "kairos:bbq-sauce", keywords: "bbq sauce" },
  { icon: "kairos:black-pepper", keywords: "black pepper" },
  { icon: "kairos:bleach", keywords: "bleach" },
  { icon: "kairos:block-cheese", keywords: "block cheese cheese cheddar" },
  { icon: "kairos:body-wash", keywords: "body wash" },
  { icon: "kairos:breadcrumbs", keywords: "breadcrumbs" },
  { icon: "kairos:brisket", keywords: "brisket beef" },
  { icon: "kairos:broth", keywords: "broth" },
  { icon: "kairos:brown-sugar", keywords: "brown sugar" },
  { icon: "kairos:brussels-sprouts", keywords: "brussels sprouts brussel sprout" },
  { icon: "kairos:butter-sticks", keywords: "butter sticks butter" },
  { icon: "kairos:canned-beans", keywords: "canned beans black kidney beans" },
  { icon: "kairos:canned-goods", keywords: "canned goods" },
  { icon: "kairos:canned-tomatoes", keywords: "canned tomatoes diced tomato" },
  { icon: "kairos:cantaloupe", keywords: "cantaloupe melon muskmelon" },
  { icon: "kairos:casserole", keywords: "casserole" },
  { icon: "kairos:cat-food", keywords: "cat food" },
  { icon: "kairos:cat-litter", keywords: "cat litter" },
  { icon: "kairos:cauliflower", keywords: "cauliflower cauli" },
  { icon: "kairos:celery", keywords: "celery stalk" },
  { icon: "kairos:cheddar", keywords: "cheddar" },
  { icon: "kairos:chicken-breast", keywords: "chicken breast boneless" },
  { icon: "kairos:chicken-thighs", keywords: "chicken thighs thigh" },
  { icon: "kairos:chicken-wings", keywords: "chicken wings wing" },
  { icon: "kairos:chili-powder", keywords: "chili powder" },
  { icon: "kairos:chips-bag", keywords: "chips bag potato chips crisps" },
  { icon: "kairos:cinnamon", keywords: "cinnamon" },
  { icon: "kairos:cleaning-spray", keywords: "cleaning spray" },
  { icon: "kairos:coconut-milk", keywords: "coconut milk coconut" },
  { icon: "kairos:cold-cuts", keywords: "cold cuts lunch meat deli sliced" },
  { icon: "kairos:conditioner", keywords: "conditioner" },
  { icon: "kairos:cooking-spray", keywords: "cooking spray pam nonstick oil" },
  { icon: "kairos:cornstarch", keywords: "cornstarch" },
  { icon: "kairos:cottage-cheese", keywords: "cottage cheese" },
  { icon: "kairos:cotton-swabs", keywords: "cotton swabs" },
  { icon: "kairos:crackers-box", keywords: "crackers box cracker" },
  { icon: "kairos:cream-cheese", keywords: "cream cheese" },
  { icon: "kairos:creamer", keywords: "creamer" },
  { icon: "kairos:cumin", keywords: "cumin" },
  { icon: "kairos:deli-ham", keywords: "deli ham ham sliced" },
  { icon: "kairos:deodorant", keywords: "deodorant" },
  { icon: "kairos:diapers", keywords: "diapers" },
  { icon: "kairos:dinner-rolls", keywords: "dinner rolls roll" },
  { icon: "kairos:dish-soap", keywords: "dish soap" },
  { icon: "kairos:dishwasher-pods", keywords: "dishwasher pods" },
  { icon: "kairos:dog-food", keywords: "dog food" },
  { icon: "kairos:dryer-sheets", keywords: "dryer sheets fabric softener" },
  { icon: "kairos:egg-noodles", keywords: "egg noodles" },
  { icon: "kairos:eggs-carton", keywords: "eggs carton eggs dozen" },
  { icon: "kairos:energy-drink", keywords: "energy drink" },
  { icon: "kairos:english-muffins", keywords: "english muffins muffin" },
  { icon: "kairos:fajitas", keywords: "fajitas" },
  { icon: "kairos:feminine-care", keywords: "feminine care" },
  { icon: "kairos:feta", keywords: "feta" },
  { icon: "kairos:filet-mignon", keywords: "filet mignon filet tenderloin" },
  { icon: "kairos:first-aid", keywords: "first aid kit" },
  { icon: "kairos:floss", keywords: "floss" },
  { icon: "kairos:flour", keywords: "flour" },
  { icon: "kairos:foil", keywords: "foil" },
  { icon: "kairos:frozen-dinner", keywords: "frozen dinner" },
  { icon: "kairos:frozen-pizza", keywords: "frozen pizza pizza" },
  { icon: "kairos:frozen-veggies", keywords: "frozen veggies" },
  { icon: "kairos:garlic-powder", keywords: "garlic powder" },
  { icon: "kairos:granola-bars", keywords: "granola bars granola protein bar" },
  { icon: "kairos:green-beans", keywords: "green beans string bean" },
  { icon: "kairos:green-onion", keywords: "green onion scallion spring onion" },
  { icon: "kairos:ground-beef", keywords: "ground beef hamburger meat mince minced" },
  { icon: "kairos:ground-sausage", keywords: "ground sausage breakfast sausage" },
  { icon: "kairos:ground-turkey", keywords: "ground turkey minced" },
  { icon: "kairos:guacamole", keywords: "guacamole guac" },
  { icon: "kairos:hamburger-buns", keywords: "hamburger buns burger bun" },
  { icon: "kairos:hand-soap", keywords: "hand soap liquid soap" },
  { icon: "kairos:honey-jar", keywords: "honey jar honey" },
  { icon: "kairos:hot-dog-buns", keywords: "hot dog buns hotdog bun" },
  { icon: "kairos:hummus", keywords: "hummus hommus" },
  { icon: "kairos:ice", keywords: "ice" },
  { icon: "kairos:italian-bread", keywords: "italian bread loaf" },
  { icon: "kairos:italian-seasoning", keywords: "italian seasoning" },
  { icon: "kairos:jam", keywords: "jam" },
  { icon: "kairos:ketchup", keywords: "ketchup" },
  { icon: "kairos:lasagna", keywords: "lasagna" },
  { icon: "kairos:laundry-detergent", keywords: "laundry detergent" },
  { icon: "kairos:light-bulbs", keywords: "light bulbs lightbulb bulb led" },
  { icon: "kairos:lotion", keywords: "lotion moisturizer" },
  { icon: "kairos:mac-and-cheese", keywords: "mac and cheese macaroni" },
  { icon: "kairos:macaroni", keywords: "macaroni" },
  { icon: "kairos:mayo", keywords: "mayo" },
  { icon: "kairos:meatballs", keywords: "meatballs" },
  { icon: "kairos:meatloaf", keywords: "meatloaf" },
  { icon: "kairos:medicine", keywords: "medicine" },
  { icon: "kairos:mozzarella", keywords: "mozzarella" },
  { icon: "kairos:mustard", keywords: "mustard" },
  { icon: "kairos:napkins", keywords: "napkins" },
  { icon: "kairos:oatmeal-canister", keywords: "oatmeal canister oats" },
  { icon: "kairos:olive-oil", keywords: "olive oil evoo extra virgin cooking oil" },
  { icon: "kairos:olives-jar", keywords: "olives jar olive" },
  { icon: "kairos:onion-powder", keywords: "onion powder" },
  { icon: "kairos:oregano", keywords: "oregano" },
  { icon: "kairos:pain-reliever", keywords: "pain reliever tylenol advil ibuprofen aspirin acetaminophen" },
  { icon: "kairos:pancake-mix", keywords: "pancake mix waffle mix" },
  { icon: "kairos:paper-plates", keywords: "paper plates disposable plate" },
  { icon: "kairos:paper-towels", keywords: "paper towels" },
  { icon: "kairos:paprika", keywords: "paprika" },
  { icon: "kairos:parmesan", keywords: "parmesan" },
  { icon: "kairos:pasta-sauce", keywords: "pasta sauce" },
  { icon: "kairos:peanut-butter", keywords: "peanut butter" },
  { icon: "kairos:penne", keywords: "penne" },
  { icon: "kairos:pepperoni", keywords: "pepperoni slices" },
  { icon: "kairos:pet-treats", keywords: "pet treats" },
  { icon: "kairos:pickles-jar", keywords: "pickles jar pickle" },
  { icon: "kairos:pita-bread", keywords: "pita bread pita pocket" },
  { icon: "kairos:plastic-cutlery", keywords: "plastic cutlery fork spoon knife utensils silverware" },
  { icon: "kairos:plastic-wrap", keywords: "plastic wrap" },
  { icon: "kairos:pork-chops", keywords: "pork chops pork chop" },
  { icon: "kairos:protein-powder", keywords: "protein powder" },
  { icon: "kairos:ravioli", keywords: "ravioli" },
  { icon: "kairos:razors", keywords: "razors" },
  { icon: "kairos:red-onion", keywords: "red onion onion purple" },
  { icon: "kairos:red-potato", keywords: "red potato potato" },
  { icon: "kairos:ribeye-steak", keywords: "ribeye steak rib eye" },
  { icon: "kairos:ribs", keywords: "ribs pork baby back rack" },
  { icon: "kairos:rice-bag", keywords: "rice bag white rice" },
  { icon: "kairos:romaine-lettuce", keywords: "romaine lettuce romaine" },
  { icon: "kairos:rotisserie-chicken", keywords: "rotisserie chicken whole roast" },
  { icon: "kairos:russet-potato", keywords: "russet potato potato baking" },
  { icon: "kairos:salad-dressing", keywords: "salad dressing" },
  { icon: "kairos:salami", keywords: "salami salame" },
  { icon: "kairos:salsa", keywords: "salsa" },
  { icon: "kairos:shampoo", keywords: "shampoo" },
  { icon: "kairos:shredded-cheese", keywords: "shredded cheese" },
  { icon: "kairos:sirloin-steak", keywords: "sirloin steak" },
  { icon: "kairos:soda-bottle", keywords: "soda bottle" },
  { icon: "kairos:soup-bowl", keywords: "soup bowl soup" },
  { icon: "kairos:sour-cream", keywords: "sour cream" },
  { icon: "kairos:soy-sauce", keywords: "soy sauce" },
  { icon: "kairos:spaghetti", keywords: "spaghetti" },
  { icon: "kairos:sparkling-water", keywords: "sparkling water" },
  { icon: "kairos:spice-jar", keywords: "spice jar" },
  { icon: "kairos:sponges", keywords: "sponges sponge scrubber" },
  { icon: "kairos:sports-drink", keywords: "sports drink" },
  { icon: "kairos:stir-fry", keywords: "stir fry" },
  { icon: "kairos:storage-bags", keywords: "storage bags" },
  { icon: "kairos:string-cheese", keywords: "string cheese" },
  { icon: "kairos:sugar", keywords: "sugar" },
  { icon: "kairos:sunscreen", keywords: "sunscreen sunblock spf" },
  { icon: "kairos:supplements", keywords: "supplements" },
  { icon: "kairos:syrup", keywords: "syrup" },
  { icon: "kairos:tacos-plate", keywords: "tacos plate taco" },
  { icon: "kairos:tissues", keywords: "tissues" },
  { icon: "kairos:tofu", keywords: "tofu bean curd" },
  { icon: "kairos:tomato-paste", keywords: "tomato paste" },
  { icon: "kairos:toothpaste", keywords: "toothpaste" },
  { icon: "kairos:tortilla-chips", keywords: "tortilla chips corn chips" },
  { icon: "kairos:tortillas", keywords: "tortillas flour tortilla wrap" },
  { icon: "kairos:trash-bags", keywords: "trash bags" },
  { icon: "kairos:vegetable-oil", keywords: "vegetable oil canola cooking oil" },
  { icon: "kairos:vinegar", keywords: "vinegar" },
  { icon: "kairos:vitamins", keywords: "vitamins" },
  { icon: "kairos:yellow-onion", keywords: "yellow onion onion" },
  { icon: "kairos:yogurt", keywords: "yogurt" },
  { icon: "kairos:ziti", keywords: "ziti" },
  { icon: "kairos:zucchini", keywords: "zucchini courgette" },
  { icon: "kairos:milk-carton", keywords: "milk carton dairy gallon half" },
  { icon: "kairos:coffee-bag", keywords: "coffee bag beans ground whole bean" },
  { icon: "kairos:wine", keywords: "wine red white bottle" },
  { icon: "kairos:beer", keywords: "beer ale lager bottle" },
  { icon: "kairos:champagne", keywords: "champagne sparkling prosecco" },
  { icon: "kairos:whiskey", keywords: "whiskey whisky scotch" },
  { icon: "kairos:bourbon", keywords: "bourbon whiskey" },
  { icon: "kairos:vodka", keywords: "vodka" },
  { icon: "kairos:gin", keywords: "gin" },
  { icon: "kairos:rum", keywords: "rum" },
  { icon: "kairos:tequila", keywords: "tequila" },
  { icon: "kairos:cocktail", keywords: "cocktail mixed drink margarita" },
  { icon: "kairos:salmon", keywords: "salmon" },
  { icon: "kairos:tuna", keywords: "tuna" },
  { icon: "kairos:tilapia", keywords: "tilapia" },
  { icon: "kairos:cod", keywords: "cod codfish" },
  { icon: "kairos:catfish", keywords: "catfish" },
  { icon: "kairos:mahi-mahi", keywords: "mahi mahi mahi dorado" },
  { icon: "kairos:shrimp", keywords: "shrimp prawn" },
  { icon: "kairos:crab-legs", keywords: "crab legs king snow crab" },
  { icon: "kairos:lobster-tail", keywords: "lobster tail lobster" },
  { icon: "kairos:scallops", keywords: "scallops" },
  { icon: "kairos:mussels", keywords: "mussels" },
  { icon: "kairos:clams", keywords: "clams" },
  { icon: "kairos:crawfish", keywords: "crawfish crayfish crawdad" },
  { icon: "kairos:fish-fillet", keywords: "fish fillet filet" },
  { icon: "kairos:fish-sticks", keywords: "fish sticks" },
  { icon: "kairos:canned-tuna", keywords: "canned tuna tuna can" },
  { icon: "kairos:imitation-crab", keywords: "imitation crab surimi krab crab stick" },
  { icon: "kairos:orange-juice", keywords: "orange juice oj" },
  { icon: "kairos:apple-juice", keywords: "apple juice" },
  { icon: "kairos:grape-juice", keywords: "grape juice" },
  { icon: "kairos:cranberry-juice", keywords: "cranberry juice" },
  { icon: "kairos:lemonade", keywords: "lemonade" },
  { icon: "kairos:sweet-tea", keywords: "sweet tea sweetened iced" },
  { icon: "kairos:iced-tea", keywords: "iced tea" },
  { icon: "kairos:kombucha", keywords: "kombucha" },
  { icon: "kairos:hot-chocolate", keywords: "hot chocolate cocoa hot cocoa" },
  { icon: "kairos:chocolate-milk", keywords: "chocolate milk" },
  { icon: "kairos:apple-cider", keywords: "apple cider cider" },
  { icon: "kairos:coconut-water", keywords: "coconut water" },
  { icon: "kairos:chocolate-chips", keywords: "chocolate chips baking chips morsels" },
  { icon: "kairos:coffee-filters", keywords: "coffee filters paper filter" },
  { icon: "kairos:k-cups", keywords: "k cups coffee pod keurig single serve" },
  { icon: "kairos:plums", keywords: "plums" },
  { icon: "kairos:pomegranate", keywords: "pomegranate" },
  { icon: "kairos:cannoli", keywords: "cannoli italian pastry" },
  { icon: "kairos:doritos", keywords: "doritos nacho chips" },
  { icon: "kairos:sunflower-seeds", keywords: "sunflower seeds seeds" },
  { icon: "kairos:almonds", keywords: "almonds nuts" },
  { icon: "kairos:cashews", keywords: "cashews nuts" },
  { icon: "kairos:walnuts", keywords: "walnuts nuts" },
  { icon: "kairos:pistachios", keywords: "pistachios nuts" },
  { icon: "kairos:beef-jerky", keywords: "beef jerky jerky dried meat snack" },
  { icon: "kairos:turkey-jerky", keywords: "turkey jerky jerky snack" },
  { icon: "kairos:protein-bar", keywords: "protein bar snack energy bar cliff clif" },
  { icon: "kairos:granola", keywords: "granola oats cereal" },
  { icon: "kairos:corn-meal", keywords: "corn meal polenta grits" },
  { icon: "kairos:heavy-cream", keywords: "heavy cream whipping cream dairy" },
  { icon: "kairos:whipped-cream-can", keywords: "whipped cream can reddi wip aerosol" },
  { icon: "kairos:whipped-cream-tub", keywords: "whipped cream tub cool whip topping" },
  { icon: "kairos:sliced-cheese", keywords: "sliced cheese american singles deli cold cut" },
  { icon: "kairos:black-olives", keywords: "black olives canned olive" },
  { icon: "kairos:distilled-water", keywords: "distilled water gallon jug purified" },
  { icon: "kairos:motor-oil", keywords: "motor oil car engine automotive" },
  { icon: "kairos:avocado-oil", keywords: "avocado oil cooking oil" },
  { icon: "kairos:car-oil-filter", keywords: "car oil filter automotive engine" },
  { icon: "kairos:car-air-filter", keywords: "car air filter automotive engine cabin" },
  { icon: "kairos:birthday-candles", keywords: "birthday candles cake candle" },
  { icon: "kairos:iceberg-lettuce", keywords: "iceberg lettuce salad head" },
  { icon: "kairos:backpacking-food", keywords: "backpacking food freeze dried camping hiking trail meal" },
];

/** Store/shop icons for the admin store picker (kairos: PNGs + a few emoji). */
export const STORE_ICON_LIBRARY: IconLibraryEntry[] = [
  { icon: "kairos:supermarket", keywords: "supermarket grocery store market" },
  { icon: "kairos:warehouse-club", keywords: "warehouse club costco sams bulk" },
  { icon: "kairos:big-box-store", keywords: "big box store walmart target department" },
  { icon: "kairos:pharmacy", keywords: "pharmacy drugstore cvs walgreens" },
  { icon: "kairos:farmers-market", keywords: "farmers market produce stand" },
  { icon: "kairos:convenience-store", keywords: "convenience store corner gas" },
  { icon: "kairos:delivery-truck", keywords: "delivery truck shipping" },
  { icon: "kairos:online-order", keywords: "online order web amazon delivery" },
  { icon: "kairos:hardware-store", keywords: "hardware home improvement" },
  { icon: "kairos:butcher-shop", keywords: "butcher meat shop" },
  { icon: "kairos:bakery-shop", keywords: "bakery bread shop" },
  { icon: "kairos:liquor-store", keywords: "liquor wine beer store" },
  { icon: "\ud83c\udfec", keywords: "store department building shop" },
  { icon: "\ud83c\udfea", keywords: "convenience store shop" },
  { icon: "\ud83d\uded2", keywords: "cart grocery shopping" },
  { icon: "\ud83c\udfe5", keywords: "pharmacy hospital medical" },
];

export type IconGuess = { icon: string; confident: boolean };

/**
 * Pick an icon for an item name. Instead of "first rule in the list wins" (which
 * let a modifier steal a compound name, e.g. "cherry tomatoes" -> cherry), collect
 * every matching rule and prefer the one whose match ends latest -- the head noun
 * of an English "modifier head" name ("cherry TOMATO", "fish SAUCE", "apple JUICE")
 * -- breaking ties toward the longer, more specific match so a phrase rule like
 * "peanut butter" beats bare "butter".
 *
 * `confident` is false when the name is genuinely ambiguous: nothing matched, or
 * two disjoint rules did (a real compound). It stays true for a single match or a
 * phrase rule that spans its components, so the admin only flags the real unknowns.
 */
export function guessIconInfo(name: string): IconGuess {
  const n = name.toLowerCase();
  const hits: { icon: string; start: number; end: number; len: number }[] = [];
  for (const [re, icon] of ICONS) {
    const m = re.exec(n);
    if (m) hits.push({ icon, start: m.index, end: m.index + m[0].length, len: m[0].length });
  }
  if (hits.length === 0) return { icon: "📦", confident: false };
  hits.sort((a, b) => b.end - a.end || b.len - a.len);
  const top = hits[0];
  const confident = hits.every((h) => h === top || (h.start >= top.start && h.end <= top.end));
  return { icon: top.icon, confident };
}

export function guessIcon(name: string): string {
  return guessIconInfo(name).icon;
}
