/**
 * Every item Kairos ships a custom `kairos:` icon for, with its canonical name.
 *
 * The add-an-item list is normally just the household's own catalog, which means
 * an item nobody has bought yet isn't offerable and gets typed (and mistyped)
 * from scratch. These are offered alongside the catalog so the whole custom-icon
 * set is pickable with the spelling the icon matcher expects.
 *
 * They are NOT catalog rows and never touch the database: picking one adds the
 * item by name through the normal path, which creates the catalog entry and
 * guesses its icon — landing on the very icon listed here. So "Re-sync catalog"
 * has nothing extra to merge, and an item the household already has wins (the
 * clients drop a suggestion whose name matches a catalog item, case-insensitively).
 *
 * Generated from the `kairos:` rules in catalog.ts — keep it in step when icons
 * are added, and mirror any change in the app's GrocerySuggestions.kt.
 */
export type GrocerySuggestion = { name: string; icon: string };

export const GROCERY_SUGGESTIONS: GrocerySuggestion[] = [
  { name: "Air freshener", icon: "kairos:air-freshener" },
  { name: "Allergy medicine", icon: "kairos:allergy-medicine" },
  { name: "Almond milk", icon: "kairos:almond-milk" },
  { name: "Almonds", icon: "kairos:almonds" },
  { name: "Apple cider", icon: "kairos:apple-cider" },
  { name: "Apple juice", icon: "kairos:apple-juice" },
  { name: "Asparagus", icon: "kairos:asparagus" },
  { name: "Avocado oil", icon: "kairos:avocado-oil" },
  { name: "Baby food", icon: "kairos:baby-food" },
  { name: "Baby formula", icon: "kairos:baby-formula" },
  { name: "Baby wipes", icon: "kairos:baby-wipes" },
  { name: "Backpacking food", icon: "kairos:backpacking-food" },
  { name: "Baking powder", icon: "kairos:baking-powder" },
  { name: "Baking soda", icon: "kairos:baking-soda" },
  { name: "Bandages", icon: "kairos:bandages" },
  { name: "Batteries", icon: "kairos:batteries-pack" },
  { name: "BBQ sauce", icon: "kairos:bbq-sauce" },
  { name: "Beef jerky", icon: "kairos:beef-jerky" },
  { name: "Beer", icon: "kairos:beer" },
  { name: "Birthday candles", icon: "kairos:birthday-candles" },
  { name: "Black olives", icon: "kairos:black-olives" },
  { name: "Black pepper", icon: "kairos:black-pepper" },
  { name: "Bleach", icon: "kairos:bleach" },
  { name: "Block cheese", icon: "kairos:block-cheese" },
  { name: "Body wash", icon: "kairos:body-wash" },
  { name: "Bourbon", icon: "kairos:bourbon" },
  { name: "Breadcrumbs", icon: "kairos:breadcrumbs" },
  { name: "Brisket", icon: "kairos:brisket" },
  { name: "Broth", icon: "kairos:broth" },
  { name: "Brown sugar", icon: "kairos:brown-sugar" },
  { name: "Brussels sprouts", icon: "kairos:brussels-sprouts" },
  { name: "Butter sticks", icon: "kairos:butter-sticks" },
  { name: "Canned beans", icon: "kairos:canned-beans" },
  { name: "Canned goods", icon: "kairos:canned-goods" },
  { name: "Canned tomatoes", icon: "kairos:canned-tomatoes" },
  { name: "Canned tuna", icon: "kairos:canned-tuna" },
  { name: "Cannoli", icon: "kairos:cannoli" },
  { name: "Cantaloupe", icon: "kairos:cantaloupe" },
  { name: "Car air filter", icon: "kairos:car-air-filter" },
  { name: "Car oil filter", icon: "kairos:car-oil-filter" },
  { name: "Cashews", icon: "kairos:cashews" },
  { name: "Casserole", icon: "kairos:casserole" },
  { name: "Cat food", icon: "kairos:cat-food" },
  { name: "Cat litter", icon: "kairos:cat-litter" },
  { name: "Catfish", icon: "kairos:catfish" },
  { name: "Cauliflower", icon: "kairos:cauliflower" },
  { name: "Celery", icon: "kairos:celery" },
  { name: "Champagne", icon: "kairos:champagne" },
  { name: "Cheddar", icon: "kairos:cheddar" },
  { name: "Chicken breast", icon: "kairos:chicken-breast" },
  { name: "Chicken thighs", icon: "kairos:chicken-thighs" },
  { name: "Chicken wings", icon: "kairos:chicken-wings" },
  { name: "Chili powder", icon: "kairos:chili-powder" },
  { name: "Chips", icon: "kairos:chips-bag" },
  { name: "Chocolate chips", icon: "kairos:chocolate-chips" },
  { name: "Chocolate milk", icon: "kairos:chocolate-milk" },
  { name: "Cinnamon", icon: "kairos:cinnamon" },
  { name: "Clams", icon: "kairos:clams" },
  { name: "Cleaning spray", icon: "kairos:cleaning-spray" },
  { name: "Cocktail", icon: "kairos:cocktail" },
  { name: "Coconut milk", icon: "kairos:coconut-milk" },
  { name: "Coconut water", icon: "kairos:coconut-water" },
  { name: "Cod", icon: "kairos:cod" },
  { name: "Coffee", icon: "kairos:coffee-bag" },
  { name: "Coffee filters", icon: "kairos:coffee-filters" },
  { name: "Cold cuts", icon: "kairos:cold-cuts" },
  { name: "Conditioner", icon: "kairos:conditioner" },
  { name: "Cooking spray", icon: "kairos:cooking-spray" },
  { name: "Cornmeal", icon: "kairos:corn-meal" },
  { name: "Cornstarch", icon: "kairos:cornstarch" },
  { name: "Cottage cheese", icon: "kairos:cottage-cheese" },
  { name: "Cotton swabs", icon: "kairos:cotton-swabs" },
  { name: "Crab legs", icon: "kairos:crab-legs" },
  { name: "Crackers", icon: "kairos:crackers-box" },
  { name: "Cranberry juice", icon: "kairos:cranberry-juice" },
  { name: "Crawfish", icon: "kairos:crawfish" },
  { name: "Cream cheese", icon: "kairos:cream-cheese" },
  { name: "Creamer", icon: "kairos:creamer" },
  { name: "Cumin", icon: "kairos:cumin" },
  { name: "Deli ham", icon: "kairos:deli-ham" },
  { name: "Deodorant", icon: "kairos:deodorant" },
  { name: "Diapers", icon: "kairos:diapers" },
  { name: "Dinner rolls", icon: "kairos:dinner-rolls" },
  { name: "Dish soap", icon: "kairos:dish-soap" },
  { name: "Dishwasher pods", icon: "kairos:dishwasher-pods" },
  { name: "Distilled water", icon: "kairos:distilled-water" },
  { name: "Dog food", icon: "kairos:dog-food" },
  { name: "Doritos", icon: "kairos:doritos" },
  { name: "Dryer sheets", icon: "kairos:dryer-sheets" },
  { name: "Egg noodles", icon: "kairos:egg-noodles" },
  { name: "Eggs", icon: "kairos:eggs-carton" },
  { name: "Energy drink", icon: "kairos:energy-drink" },
  { name: "English muffins", icon: "kairos:english-muffins" },
  { name: "Fajitas", icon: "kairos:fajitas" },
  { name: "Feminine care", icon: "kairos:feminine-care" },
  { name: "Feta", icon: "kairos:feta" },
  { name: "Filet mignon", icon: "kairos:filet-mignon" },
  { name: "First aid supplies", icon: "kairos:first-aid" },
  { name: "Fish fillets", icon: "kairos:fish-fillet" },
  { name: "Fish sticks", icon: "kairos:fish-sticks" },
  { name: "Floss", icon: "kairos:floss" },
  { name: "Flour", icon: "kairos:flour" },
  { name: "Foil", icon: "kairos:foil" },
  { name: "Frozen dinner", icon: "kairos:frozen-dinner" },
  { name: "Frozen pizza", icon: "kairos:frozen-pizza" },
  { name: "Frozen vegetables", icon: "kairos:frozen-veggies" },
  { name: "Garlic powder", icon: "kairos:garlic-powder" },
  { name: "Gin", icon: "kairos:gin" },
  { name: "Granola", icon: "kairos:granola" },
  { name: "Granola bars", icon: "kairos:granola-bars" },
  { name: "Grape juice", icon: "kairos:grape-juice" },
  { name: "Green beans", icon: "kairos:green-beans" },
  { name: "Green onion", icon: "kairos:green-onion" },
  { name: "Ground beef", icon: "kairos:ground-beef" },
  { name: "Ground sausage", icon: "kairos:ground-sausage" },
  { name: "Ground turkey", icon: "kairos:ground-turkey" },
  { name: "Guacamole", icon: "kairos:guacamole" },
  { name: "Hamburger buns", icon: "kairos:hamburger-buns" },
  { name: "Hand soap", icon: "kairos:hand-soap" },
  { name: "Heavy cream", icon: "kairos:heavy-cream" },
  { name: "Honey", icon: "kairos:honey-jar" },
  { name: "Hot chocolate", icon: "kairos:hot-chocolate" },
  { name: "Hot dog buns", icon: "kairos:hot-dog-buns" },
  { name: "Hummus", icon: "kairos:hummus" },
  { name: "Ice", icon: "kairos:ice" },
  { name: "Iceberg lettuce", icon: "kairos:iceberg-lettuce" },
  { name: "Iced tea", icon: "kairos:iced-tea" },
  { name: "Imitation crab", icon: "kairos:imitation-crab" },
  { name: "Italian bread", icon: "kairos:italian-bread" },
  { name: "Italian seasoning", icon: "kairos:italian-seasoning" },
  { name: "Jam", icon: "kairos:jam" },
  { name: "K-Cups", icon: "kairos:k-cups" },
  { name: "Ketchup", icon: "kairos:ketchup" },
  { name: "Kombucha", icon: "kairos:kombucha" },
  { name: "Lasagna", icon: "kairos:lasagna" },
  { name: "Laundry detergent", icon: "kairos:laundry-detergent" },
  { name: "Lemonade", icon: "kairos:lemonade" },
  { name: "Light bulbs", icon: "kairos:light-bulbs" },
  { name: "Lobster tail", icon: "kairos:lobster-tail" },
  { name: "Lotion", icon: "kairos:lotion" },
  { name: "Mac and cheese", icon: "kairos:mac-and-cheese" },
  { name: "Macaroni", icon: "kairos:macaroni" },
  { name: "Mahi-mahi", icon: "kairos:mahi-mahi" },
  { name: "Mayonnaise", icon: "kairos:mayo" },
  { name: "Meatballs", icon: "kairos:meatballs" },
  { name: "Meatloaf", icon: "kairos:meatloaf" },
  { name: "Medicine", icon: "kairos:medicine" },
  { name: "Milk", icon: "kairos:milk-carton" },
  { name: "Motor oil", icon: "kairos:motor-oil" },
  { name: "Mozzarella", icon: "kairos:mozzarella" },
  { name: "Mussels", icon: "kairos:mussels" },
  { name: "Mustard", icon: "kairos:mustard" },
  { name: "Napkins", icon: "kairos:napkins" },
  { name: "Oatmeal", icon: "kairos:oatmeal-canister" },
  { name: "Olive oil", icon: "kairos:olive-oil" },
  { name: "Olives", icon: "kairos:olives-jar" },
  { name: "Onion powder", icon: "kairos:onion-powder" },
  { name: "Orange juice", icon: "kairos:orange-juice" },
  { name: "Oregano", icon: "kairos:oregano" },
  { name: "Pain reliever", icon: "kairos:pain-reliever" },
  { name: "Pancake mix", icon: "kairos:pancake-mix" },
  { name: "Paper plates", icon: "kairos:paper-plates" },
  { name: "Paper towels", icon: "kairos:paper-towels" },
  { name: "Paprika", icon: "kairos:paprika" },
  { name: "Parmesan", icon: "kairos:parmesan" },
  { name: "Pasta sauce", icon: "kairos:pasta-sauce" },
  { name: "Peanut butter", icon: "kairos:peanut-butter" },
  { name: "Penne", icon: "kairos:penne" },
  { name: "Pepperoni", icon: "kairos:pepperoni" },
  { name: "Pet treats", icon: "kairos:pet-treats" },
  { name: "Pickles", icon: "kairos:pickles-jar" },
  { name: "Pistachios", icon: "kairos:pistachios" },
  { name: "Pita bread", icon: "kairos:pita-bread" },
  { name: "Plastic cutlery", icon: "kairos:plastic-cutlery" },
  { name: "Plastic wrap", icon: "kairos:plastic-wrap" },
  { name: "Plums", icon: "kairos:plums" },
  { name: "Pomegranate", icon: "kairos:pomegranate" },
  { name: "Pork chops", icon: "kairos:pork-chops" },
  { name: "Protein bar", icon: "kairos:protein-bar" },
  { name: "Protein powder", icon: "kairos:protein-powder" },
  { name: "Ravioli", icon: "kairos:ravioli" },
  { name: "Razors", icon: "kairos:razors" },
  { name: "Red onion", icon: "kairos:red-onion" },
  { name: "Red potato", icon: "kairos:red-potato" },
  { name: "Ribeye steak", icon: "kairos:ribeye-steak" },
  { name: "Ribs", icon: "kairos:ribs" },
  { name: "Rice", icon: "kairos:rice-bag" },
  { name: "Romaine lettuce", icon: "kairos:romaine-lettuce" },
  { name: "Rotisserie chicken", icon: "kairos:rotisserie-chicken" },
  { name: "Rum", icon: "kairos:rum" },
  { name: "Russet potato", icon: "kairos:russet-potato" },
  { name: "Salad dressing", icon: "kairos:salad-dressing" },
  { name: "Salami", icon: "kairos:salami" },
  { name: "Salmon", icon: "kairos:salmon" },
  { name: "Salsa", icon: "kairos:salsa" },
  { name: "Scallops", icon: "kairos:scallops" },
  { name: "Shampoo", icon: "kairos:shampoo" },
  { name: "Shredded cheese", icon: "kairos:shredded-cheese" },
  { name: "Shrimp", icon: "kairos:shrimp" },
  { name: "Sirloin steak", icon: "kairos:sirloin-steak" },
  { name: "Sliced cheese", icon: "kairos:sliced-cheese" },
  { name: "Soda", icon: "kairos:soda-bottle" },
  { name: "Soup", icon: "kairos:soup-bowl" },
  { name: "Sour cream", icon: "kairos:sour-cream" },
  { name: "Soy sauce", icon: "kairos:soy-sauce" },
  { name: "Spaghetti", icon: "kairos:spaghetti" },
  { name: "Sparkling water", icon: "kairos:sparkling-water" },
  { name: "Spices", icon: "kairos:spice-jar" },
  { name: "Sponges", icon: "kairos:sponges" },
  { name: "Sports drink", icon: "kairos:sports-drink" },
  { name: "Stir-fry", icon: "kairos:stir-fry" },
  { name: "Storage bags", icon: "kairos:storage-bags" },
  { name: "String cheese", icon: "kairos:string-cheese" },
  { name: "Sugar", icon: "kairos:sugar" },
  { name: "Sunflower seeds", icon: "kairos:sunflower-seeds" },
  { name: "Sunscreen", icon: "kairos:sunscreen" },
  { name: "Supplements", icon: "kairos:supplements" },
  { name: "Sweet tea", icon: "kairos:sweet-tea" },
  { name: "Syrup", icon: "kairos:syrup" },
  { name: "Tacos", icon: "kairos:tacos-plate" },
  { name: "Tequila", icon: "kairos:tequila" },
  { name: "Tilapia", icon: "kairos:tilapia" },
  { name: "Tissues", icon: "kairos:tissues" },
  { name: "Tofu", icon: "kairos:tofu" },
  { name: "Tomato paste", icon: "kairos:tomato-paste" },
  { name: "Toothpaste", icon: "kairos:toothpaste" },
  { name: "Tortilla chips", icon: "kairos:tortilla-chips" },
  { name: "Tortillas", icon: "kairos:tortillas" },
  { name: "Trash bags", icon: "kairos:trash-bags" },
  { name: "Tuna", icon: "kairos:tuna" },
  { name: "Turkey jerky", icon: "kairos:turkey-jerky" },
  { name: "Vegetable oil", icon: "kairos:vegetable-oil" },
  { name: "Vinegar", icon: "kairos:vinegar" },
  { name: "Vitamins", icon: "kairos:vitamins" },
  { name: "Vodka", icon: "kairos:vodka" },
  { name: "Walnuts", icon: "kairos:walnuts" },
  { name: "Whipped cream can", icon: "kairos:whipped-cream-can" },
  { name: "Whipped cream tub", icon: "kairos:whipped-cream-tub" },
  { name: "Whiskey", icon: "kairos:whiskey" },
  { name: "Wine", icon: "kairos:wine" },
  { name: "Yellow onion", icon: "kairos:yellow-onion" },
  { name: "Yogurt", icon: "kairos:yogurt" },
  { name: "Ziti", icon: "kairos:ziti" },
  { name: "Zucchini", icon: "kairos:zucchini" },
];
